[package]
name = "resume-generator-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
printpdf = "0.7.0"
regex = "1.5" 